name: Makefile CI

on:
  push:
    branches: [ "assignment2/submission" ]
  pull_request:
    branches: [ "assignment2/submission" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run:
          sudo apt-get update && sudo apt-get install -y 
          build-essential 
          cmake 
          gcc 
          g++ 
          gdb 
          clang
          libeigen3-dev 
          libxerces-c-dev
          && sudo apt-get clean

      - name: build and run the project
        run:
          mkdir build
          && cd build
          && cmake ..
          && make




